import { Stack, Text } from '@chakra-ui/react'

export const ClaimMetadata = ({metadata}) => (
    <Stack
      direction="row"
      justify="space-between"
      align="flex-end"
      spacing="12px"
      alignSelf="stretch"
    >
      <Stack
        direction="column"
        justify="flex-start"
        align="flex-start"
        spacing="4px"
        flex="1"
      >
        <Stack
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="4px"
        >
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="regular"
            fontSize="12px"
            color="#414243"
          >
            Author:
          </Text>
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="semibold"
            fontSize="12px"
            color="#000000"
          >
            {metadata.author}
          </Text>
        </Stack>
        <Stack
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="4px"
        >
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="regular"
            fontSize="12px"
            color="#414243"
          >
            Source:
          </Text>
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="semibold"
            fontSize="12px"
            color="#000000"
          >
            {metadata.source}
          </Text>
        </Stack>
        <Stack
          direction="row"
          justify="flex-start"
          align="flex-start"
          spacing="4px"
        >
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="regular"
            fontSize="12px"
            color="#414243"
          >
            Date of the statement
          </Text>
          <Text
            fontFamily="Inter"
            lineHeight="1.33"
            fontWeight="semibold"
            fontSize="12px"
            color="#000000"
          >
            {metadata.date}
          </Text>
        </Stack>
      </Stack>
    </Stack>
)
